---
title: "Initial Brainstorm and Resources"
output: github_document
---

*Note: The two bolded links are my favorites*

## Random Forests

* **[Comparison between convolutional neural networks and random forest for local climate zone classification in mega urban areas using Landsat images](https://doi.org/10.1016/j.isprsjprs.2019.09.009)**
  + Complicated
  + Brings up [World Urban Database and Acess Portal Tools](http://www.wudapt.org/) which feels more accessible? 
* **[A comparison of random forest variable selection methods for classification prediction modeling](https://doi.org/10.1016/j.eswa.2019.05.028)**
* General resources
  + [Random Forests for Complete Beginners](https://victorzhou.com/blog/intro-to-random-forests/)
  + Everything says to try learning about RFs using [scikit learn](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html) and I'm not quite clear on how to use it other than just running the code at the bottom (which may be helpful enough)
  + [Deep Learning Texbook](https://www.deeplearningbook.org/)
  + [Random Forest in R - Cory Maklin](https://towardsdatascience.com/random-forest-in-r-f66adf80ec9). useful at bottom of page
  + [Random Forests - Leo Breiman and Adele Cutler](https://www.stat.berkeley.edu/~breiman/RandomForests/cc_home.htm) 

## Bayesian Hierarchical Models

* Most everything I found here felt very theoretical and I had a hard time following
* [A Bayesian hierarchical model for urban air quality prediction under uncertainty](https://doi.org/10.1016/j.atmosenv.2008.08.018). Compares MLR with BHM (kind of ? )
* [A Bayesian hierarchical model for multiple imputation of urban spatiotemporal groundwater levels](https://doi.org/10.1016/j.spl.2018.07.023)
* [Prediction of land use changes with Bayesian spatial modeling from the perspective of urban climate](https://doi.org/10.1016/j.uclim.2019.100569)
